name: Main
on: 
  push:
    branches:
      - "main"

jobs:
  first_job: # Setting a custom job id
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: |
          echo "Nice to meet you!" > hello
  second: 
    name: My Second Job
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: |
          cat hello